# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9263ba6c241988d9daf8fc6cb65f77ff8a4b08d922d0d3d4b3e5919ae86d951d9d820b0eca8ba4373d2e84fcbaccc8a5295e52e6d3883791f86a787e5ed43977

test:
  secret_key_base: 51ccc18705ff7e05b68941cc96f642ad949eebd60c0b691e1dd24b20c3c241ab526160225a131e7b6d30b5ff2e4c58eb7c1c0b13366dd7bb8cc2866e9c0af90e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
